name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install docker
      run: sudo apt-get install docker
    - name: docker pull
      run: docker pull phyzli/ubuntu18.04_xfce4_vnc4server_synopsys2016:latest
    - name: make check
      run: echo hello3
    - name: make distcheck
      run: echo hello4
